# Railway configuration for AutoBot Manager
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3001"
FRONTEND_URL = "https://your-app-name.railway.app"
LOG_LEVEL = "info"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"