# Render configuration
services:
  - type: web
    name: autobot-manager-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: your-db-host
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://your-app-name.onrender.com

  - type: web
    name: autobot-manager-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://autobot-manager-backend.onrender.com