-- Simple fix: Add all missing columns to Users table
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "githubUsername" VARCHAR(255) DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "githubAvatar" TEXT DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "cursorApiKey" TEXT DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "firstName" VARCHAR(255) DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "lastName" VARCHAR(255) DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "role" VARCHAR(20) DEFAULT 'user';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "lastLogin" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "preferences" JSONB DEFAULT '{}';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW();